장고실습/0406_django_form_장고컴백/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), #GET/POST
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'), #GET/POST
]

장고실습/0406_django_form_장고컴백/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

장고실습/0406_django_form_장고컴백/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

장고실습/0406_django_form_장고컴백/articles/forms.py
from distutils.log import error
from tkinter import Widget
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'my-title',
                'placeholder' : 'enter the title',
                'maxlength' : 10,
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class' : 'my-content form-control', #form-control 부트스트랩 스타일 지정 클래스
                'rows' : 5,
                'cols' : 50,
            }
        ),
        error_messages={
            'required' : 'Please enter your content!!!',
        }
    )

    class Meta: 
        model = Article
        fields = '__all__' #사용자로부터 받는 모든 모델필드를 출력하게됨(지금은title,content)
        #exclude = ('title',) #제외하고 싶을 때는 한개를 제외하는게 더 효율적임

# class ArticleForm(forms.Form):
#    REGION_A = 'sl'
#    REGION_B = 'dj'
#    REGION_C = 'gj'
#    REGIONS_CHOCIES = [
#        (REGION_A,'서울'), #사용자가 서울을 클릭하면 SL이 넘어옴
#        (REGION_B,'대전'), 
#        (REGION_C,'광주'), 
#    ]
#    title = forms.CharField(max_length=10)
#    content = forms.CharField(widget=forms.Textarea)
#    region = forms.ChoiceField(choices=REGIONS_CHOCIES, widget=forms.CheckboxSelectMultiple)
#    region = forms.ChoiceField(choices=REGIONS_CHOCIES) #얘도 가능 디폴트가 설렉트

장고실습/0406_django_form_장고컴백/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm
# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


# def new(request):


def create(request):
    if request.method == 'POST':
        #create
        form = ArticleForm(request.POST)
        # 유효성검사
        if form.is_valid():
            article = form.save() #save의 리턴값에 article이 존재 #모델폼의 save 메소드는 이전에 쓰던 article.save() 이거랑은 또 다름
            return redirect('articles:detail', article.pk)
        #print(form.errors) #글자크기가 넘었다고 에러를 알려주기도함
        
        
    else:
        #new
        form = ArticleForm()
    context = {
            'form' : form, #유효성 통과를 못한 FORM(에러메시지)과 그냥 인스턴스 두가지로 나눠서 받아짐/ 인덴테이션을 마지막 리턴과 같은 선상에 둬야됨

    }
    return render(request, 'articles/create.html',context)






def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)


# def edit(request, pk):
#     article = Article.objects.get(pk=pk)
#     context = {
#         'article': article,
#     }
#     return render(request, 'articles/edit.html', context)


def update(request, pk):
    if request.method == 'POST':
        #update
        article = Article.objects.get(pk=pk)
        form = ArticleForm(request.POST, instance=article) #인스턴스가 있다고 인식이 되야 수정이됨, 생성대신
        # 유효성검사
        if form.is_valid():
            article = form.save() #save의 리턴값에 article이 존재 #모델폼의 save 메소드는 이전에 쓰던 article.save() 이거랑은 또 다름
            return redirect('articles:detail', article.pk)

    else:
        #edit
        article = Article.objects.get(pk=pk)
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form' : form,
    }
    return render(request, 'articles/update.html', context)

장고실습/0406_django_form_장고컴백/articles/templates/articles/create.html
{% extends 'base.html' %}


{% block content %}
  <h1>CREATE</h1>
  <hr>
  <form action="{% url 'articles:create' %}" method="POST"> <!--action에 없어도 자기자신 url로 가서 작동은 하지만 명시적으로 써주길-->
    {% csrf_token %}
    {{ form.as_p }}
    {% comment %} <label for="title">Title: </label>
    <input type="text" id="title" name="title"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea> {% endcomment %}
    <input type="submit">
  </form>

  <hr>
    <h2>1. rendering fields manually</h2>
      <form action="{% url 'articles:create' %}" method="POST"> <!--action에 없어도 자기자신 url로 가서 작동은 하지만 명시적으로 써주길-->
        {% csrf_token %}
        <div>
          {{ form.title.errors }}
          {{ form.title.label_tag  }}
          {{ form.title  }}
        </div>
        <div>
          {{ form.content.errors }}
          {{ form.content.label_tag  }}
          {{ form.content }}
        </div>

        <input type="submit">
      </form>
  

      <h2>2. looping over the form's fields</h2>
      <form action="{% url 'articles:create' %}" method="POST"> <!--action에 없어도 자기자신 url로 가서 작동은 하지만 명시적으로 써주길-->
        {% csrf_token %}
        {% for field in form  %}
          {% if field.errors %} {% comment %}에러가 존재한다면{% endcomment %}
            {% for error in field.errors %}
              <div class="alert alert-primary" role="alert"> {{ error|escape }} </div>
            {% endfor %}
          {% endif %}
          {% comment %} {{ field.errors }} {% endcomment %}
          <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
        </div>
        {% endfor %}
        <input type="submit">
      </form>



  <a href="{% url 'articles:index' %}">back</a>
{% endblock content %}

장고실습/0406_django_form_장고컴백/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h3>{{ article.pk }}번째 글</h3>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">수정</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock content %}

장고실습/0406_django_form_장고컴백/articles/templates/articles/index.html
{% extends 'base.html' %}


{% block content %}
  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">create</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>  
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
    <hr>
  {% endfor %}
{% endblock content %}

장고실습/0406_django_form_장고컴백/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>EDIT</h1>
  <hr>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {% comment %} {{ form.as_p }} {% endcomment %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit="Submit" reset="Cancel" %}{% endbuttons %}
    {% comment %} <label for="title">Title: </label>
    <input type="text" id="title" name="title" value="{{ article.title }}"><br>
    <label for="content">Content: </label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea> {% endcomment %}
    <input type="submit">
  </form>
  <a href="{% url 'articles:detail' article.pk %}">back</a>
{% endblock content %}

장고실습/0406_django_form_장고컴백/templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  {% bootstrap_javascript %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>