복습/0310_workshop/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns =[
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),

    
]

복습/0310_workshop/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title #개발자가 보기 좋게 #객체명으로 안 뜨고 title로 뜨도록
    

복습/0310_workshop/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
import pkg_resources
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)



def new(request):

    if request.method == 'POST' :


        title = request.POST.get('title') #QueryDict 형태로 들어있음
        content = request.POST.get('content') #QueryDict 형태로 들어있음
        
 
        article = Article()
        article.title = title
        article.content = content
        #db에 반영
        article.save()

        return redirect('articles:detail', article.pk) #

    return render(request, 'articles/new.html') 

def detail(request, article_pk):

    article = get_object_or_404(Article, pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)


def delete(request, article_pk):
    #특정 게시글 조회
    # article = Article.objects.get(pk=article_pk)
    if request.method == 'POST': #조건분기!!!!
        article = get_object_or_404(Article, pk=article_pk)
        article.delete()

    return redirect('articles:index')

def edit(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
 
    article = get_object_or_404(Article, pk=article_pk)
    if request.method == 'POST':
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()

        return redirect('articles:detail', article.pk)
    else: #기존에 수정해야할 내용이 무엇이었는지 보여주기 위해서 들어가야함
        context = {
            'article' : article
        }
    return render(request, 'articles/edit.html',context)

복습/0310_workshop/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>DETAIL</h1>
  <P>제목 : {{ article.title }}</P>
  <P>내용</P>
  <P> {{ article.content}} </P>
  <p>작성일 : {{ article.created_at }} </p>
  <p>수정일 : {{ article.updated_at }} </p>
  <hr>
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a>

  <form action=" {%url 'articles:delete' article.pk %} " method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE" style="background-color:transparent;  border:0px transparent solid;" >
  </form>
  <a href=" {% url 'articles:index'  %} ">BACK</a>

{% endblock content %}

복습/0310_workshop/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
 <h1>EDIT</h1>
 <form action="" method="POST">
  <!--input type:hidden--> 
  {% csrf_token %}
  <label for="title">TITLE : </label>
  <input type="text" id="title" name="title" value="{{ article.title }}"> <br>
  
  <label for="content">CONTENT : </label>
  <textarea id="content" name="content" cols="30" rows="10" >{{ article.content }}</textarea>
  <br>

  <input type="submit" value="수정">
 </form>
{% endblock content %}

복습/0310_workshop/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:new' %}">NEW</a> 
  {% for article in articles %}
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <a href=" {% url 'articles:detail' article.pk %} ">DETAIL</a>
    <hr>
  {% endfor %}
{% endblock content %}

복습/0310_workshop/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>
  

  <form action="" method='POST'> 
  
    {% csrf_token %}
    <label for="title">TITLE : </label>
    <input type="text" id='title' name="title"> <br>

    <label for="content">CONTENT : </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea> <br>

    <input type="submit" value="작성">
  </form>
  <a href=" {% url 'articles:index'  %} ">BACK</a>
{% endblock content %}